### ISSUE TITLE
Synchronous XMLHttpRequest warning

### ISSUE THREAD

**Issue by magglomag** [coderifous/jquery-localize#81]
Hi,

I get the following warning when implementing the plugin with `$( '[data-localize]' ).localize( 'content' );`:

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Can anybody help out how to avoid that?

**Comment by kropsi** [comment]
The same problem here

**Comment by dimitriscsd** [comment]
Same here and pretty serious problem now as this functionality will be deprecated during September 2016

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
jquery-1.9.1.js:8526 Invoking 'send()' on a sync XHR during microtask execution is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5647113010544640 for more details.

**Comment by bigt11** [comment]
+1 I wont be able to use this until it get tweaked.  An ETA??

**Comment by dimitriscsd** [comment]
We are getting closer and closer to the deprecation date. Does the author plan on fixing this or do we need to go custom or find another library?

All you need to do to be honest is switch the async: false option in the ajax call with a callback.

I tried looking in the code myself to see if I can fix it but from what I understand it's written in coffeescript?

**Comment by dimitriscsd** [comment]
Chrome 54 is out today. Any update on this?

**Comment by dimitriscsd** [comment]
Thank you for this Jim. Will try the new code soon :)

**Comment by coderifous** [comment]
@dimitriscsd Sorry I couldn't get to it sooner!
